import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

import { extractCustomizerParameters } from "../../../src/application/parameters/customizer-parser";
import {
  decodeParameterSets,
  encodeParameterSets,
  ParameterSetFormatError,
} from "../../../src/application/parameters/parameter-set-codec";

const parameters = extractCustomizerParameters(
  `width = 60; enabled = true; title = "Box"; point = [0, 1]; cube(width);`,
);
const stockFixturePath = fileURLToPath(
  new URL("../../fixtures/customizer/stock-parameter-set.json", import.meta.url),
);
const scadmillFixturePath = fileURLToPath(
  new URL("../../fixtures/customizer/scadmill-parameter-set.json", import.meta.url),
);

describe("OpenSCAD parameter-set JSON v1", () => {
  it("writes the stock version-1 shape with every parameter value represented by a JSON string", () => {
    const encoded = encodeParameterSets([
      {
        name: "Tall",
        values: { width: 100.5, enabled: false, title: "Shipping", point: [-1, 2.25] },
      },
    ]);

    expect(`${encoded}\n`).toBe(`{
  "parameterSets": {
    "Tall": {
      "width": "100.5",
      "enabled": "false",
      "title": "Shipping",
      "point": "[-1, 2.25]"
    }
  },
  "fileFormatVersion": "1"
}\n`);
    expect(decodeParameterSets(encoded, parameters)).toEqual([
      {
        name: "Tall",
        values: { width: 100.5, enabled: false, title: "Shipping", point: [-1, 2.25] },
      },
    ]);
  });

  it("loads a stock-shaped fixture and ignores values for parameters no longer present", () => {
    const stock = readFileSync(stockFixturePath, "utf8");

    expect(decodeParameterSets(stock, parameters)).toEqual([
      {
        name: "Compact",
        values: { width: 25, enabled: true, title: "Carry-on", point: [3, 4] },
      },
    ]);
  });

  it("retains Hidden values from an imported set for future visibility", () => {
    const hiddenParameters = extractCustomizerParameters(
      `width = 60; /* [Hidden] */ secret = 7; cube(width);`,
    );
    const encoded = JSON.stringify({
      parameterSets: { Imported: { width: "25", secret: "99" } },
      fileFormatVersion: "1",
    });

    expect(decodeParameterSets(encoded, hiddenParameters)).toEqual([
      { name: "Imported", values: { width: 25, secret: 99 } },
    ]);
  });

  it("keeps the once-per-release stock round-trip fixture generated by the app codec", () => {
    const encoded = encodeParameterSets([{
      name: "Compact",
      values: { width: 25, height: 4, enabled: true },
    }]);
    expect(`${encoded}\n`).toBe(readFileSync(scadmillFixturePath, "utf8"));
  });

  it.each([
    ["invalid JSON", "{"],
    ["wrong version", JSON.stringify({ parameterSets: {}, fileFormatVersion: "2" })],
    ["unknown top-level key", JSON.stringify({ parameterSets: {}, fileFormatVersion: "1", extra: true })],
    ["array sets", JSON.stringify({ parameterSets: [], fileFormatVersion: "1" })],
    ["non-string stored value", JSON.stringify({ parameterSets: { Bad: { width: 3 } }, fileFormatVersion: "1" })],
    ["non-identifier key", '{"parameterSets":{"Safe":{"bad-name":"3"}},"fileFormatVersion":"1"}'],
    ["non-finite number", JSON.stringify({ parameterSets: { Bad: { width: "1e999" } }, fileFormatVersion: "1" })],
    ["wrong boolean", JSON.stringify({ parameterSets: { Bad: { enabled: "yes" } }, fileFormatVersion: "1" })],
    ["wrong vector size", JSON.stringify({ parameterSets: { Bad: { point: "[1, 2, 3]" } }, fileFormatVersion: "1" })],
  ])("rejects %s", (_caseName, source) => {
    expect(() => decodeParameterSets(source, parameters)).toThrow(ParameterSetFormatError);
  });

  it("rejects hostile or non-finite values while encoding", () => {
    expect(() =>
      encodeParameterSets([{ name: "", values: { width: 1 } }]),
    ).toThrow(ParameterSetFormatError);
    expect(() =>
      encodeParameterSets([{ name: "Bad", values: { width: Number.POSITIVE_INFINITY } }]),
    ).toThrow(ParameterSetFormatError);
  });

  it("round-trips valid prototype-shaped OpenSCAD identifiers as inert own keys", () => {
    const specialParameters = extractCustomizerParameters(
      "constructor = 1; prototype = 2; __proto__ = [0, 1]; $fn = 48; cube(constructor);",
    );
    const values = JSON.parse(
      '{"constructor":3,"prototype":4,"__proto__":[5,6],"$fn":64}',
    ) as Record<string, number | readonly number[]>;

    const encoded = encodeParameterSets([{ name: "constructor", values }]);
    const decoded = decodeParameterSets(encoded, specialParameters);

    expect(decoded).toHaveLength(1);
    expect(decoded[0]?.name).toBe("constructor");
    expect(Object.getPrototypeOf(decoded[0]?.values)).toBe(Object.prototype);
    expect(Object.hasOwn(decoded[0]?.values ?? {}, "__proto__")).toBe(true);
    expect(decoded[0]?.values).toEqual(
      JSON.parse('{"constructor":3,"prototype":4,"__proto__":[5,6],"$fn":64}'),
    );
  });

  it.each(["$", "a$b", "$$fn"])("rejects non-OpenSCAD parameter identifier %s", (name) => {
    const values = Object.fromEntries([[name, 1]]);
    expect(() => encodeParameterSets([{ name: "Invalid", values }])).toThrow(
      ParameterSetFormatError,
    );
  });
});
