import type { Metadata } from "next";
import { Footer, Header, ReleaseBar } from "../shared";
import { RELEASE } from "../../lib/release";

export const metadata: Metadata = { title: "User manual", description: `ScadMill ${RELEASE.version} manual: plain-language setup, technical reference, and architecture.` };

function Toc() {
  return <aside className="toc"><strong>In this manual</strong><a href="#nontechnical">1. Start here</a><a href="#technical">2. Technical reference</a><a href="#architecture">3. Architecture</a><a href="#troubleshooting">4. Troubleshooting</a><a href="#uninstall">5. Uninstall</a></aside>;
}

export default function Manual() {
  return <main><Header /><ReleaseBar /><div className="doc-hero shell"><p className="eyebrow">Official user manual</p><h1>From first model to technical reference.</h1><p>For ScadMill {RELEASE.version} · Windows x64 public beta</p></div><div className="doc-layout shell"><Toc /><article className="prose">
    <section id="nontechnical"><p className="section-number">PART 1 · NON-TECHNICAL GUIDE</p><h2>Start here</h2><p>ScadMill is a workbench for OpenSCAD: you describe an object in readable text, then render and inspect the resulting geometry. Your <code>.scad</code> source remains ordinary OpenSCAD source.</p><h3>What you need</h3><ol><li>64-bit Windows 10 or 11.</li><li>The signed ScadMill installer ({RELEASE.sizeHuman}).</li><li>The separate official OpenSCAD {RELEASE.engineVersion} snapshot for rendering and export.</li></ol><div className="callout warning"><strong>Beta reality check</strong><p>This is a real public beta, not a finished cross-platform release. Back up projects. There is no macOS, Linux, or public browser build yet.</p></div><h3>Install ScadMill</h3><ol><li><a href={RELEASE.download}>Download the signed installer</a>.</li><li>In PowerShell, run <code>Get-FileHash -Algorithm SHA256 .\{RELEASE.filename}</code>.</li><li>Continue only if the result is <code>{RELEASE.sha256}</code>.</li><li>Open the installer. Windows should report a valid signature from {RELEASE.signer}.</li></ol><h3>Connect OpenSCAD</h3><p>ScadMill intentionally does not bundle or replace OpenSCAD. Download the exact engine and verify its hashes using the <a href={`${RELEASE.github}/blob/main/docs/WINDOWS-BETA.md#install-the-required-openscad-engine`}>engine setup guide</a>. In ScadMill, choose <strong>Configure engine</strong>, select the verified <code>openscad.exe</code>, and confirm the status shows OpenSCAD {RELEASE.engineVersion}.</p><h3>Make your first model</h3><ol><li>Choose a sample or create a blank file.</li><li>Enter <code>cube([20, 20, 20]);</code>.</li><li>Press <kbd>F5</kbd> for a fast preview.</li><li>Orbit, pan, zoom, fit, or measure in the viewer.</li><li>Press <kbd>F6</kbd> for full-quality geometry before export.</li></ol><h3>Save and export</h3><p>Open or create a project folder, save the <code>.scad</code> file, then use Export for 3MF, STL, OFF, AMF, SVG, DXF, or PNG when appropriate to the model. Exports always come from a full render, never preview geometry.</p></section>
    <section id="technical"><p className="section-number">PART 2 · TECHNICAL REFERENCE</p><h2>How to work efficiently</h2><h3>Editor and projects</h3><p>Tabs keep independent edit and undo state. Project-relative <code>include</code> and <code>use</code> dependencies are indexed for completions and staged with binary assets for the native engine. Diagnostics link back to project files. Recovery buffers protect unsaved edits; external file changes can be reconciled per hunk.</p><h3>Preview, full render, and cancellation</h3><p><kbd>F5</kbd> uses preview policy: the fastest available backend, a shorter timeout, and a preview-only facet cap. <kbd>F6</kbd> applies no quality override and is the only source for exports. Superseded, cancelled, stale, and failed results remain explicit in run history.</p><h3>Customizer</h3><p>Top-level stock OpenSCAD Customizer annotations become typed controls. Temporary overrides do not rewrite source. Use the explicit write action to place chosen values into assignments. Parameter sets use stock JSON format.</p><h3>Viewer and comparison</h3><p>The 3D viewer reads real STL output and supports axis views, perspective or orthographic projection, bounds, measurement, pinned notes, and PNG capture. The 2D viewer displays sanitized engine-produced SVG. Successful renders compare geometry identity and, when available, volume, bounds, and triangle changes.</p><h3>Animation</h3><p>An active model using executable <code>$t</code> gains a 100-frame animation bar mapping frames to values 0.00–0.99. Rendering is sequential and backpressured; pause cancels the in-flight frame rather than building a queue.</p><h3>AI and MCP are optional</h3><p>Named OpenAI-compatible, Anthropic, or local provider configurations hold separate secrets. Desktop secrets use Windows Credential Manager. Only the conversation and context you select are sent directly to that provider; ScadMill runs no proxy. Proposed source edits can be reviewed per hunk. The local MCP bridge is desktop-only, off by default, and mutation permissions are explicit and session-bounded.</p><h3>Data and privacy</h3><p>ScadMill has no telemetry. Project files, engine output, recovery buffers, and local settings stay on the computer. Durable render caching is off by default and enabled per project. AI and explicit download/update features are the only designed network paths relevant to this beta; the updater itself is later work.</p></section>
    <section id="architecture"><p className="section-number">PART 3 · ARCHITECTURE</p><h2>Why the product is built this way</h2><p>The React application owns interaction and product state. Capability-shaped ports separate that state from desktop-specific adapters. The Tauri shell provides trusted local file, process, credential, dialog, menu, and window operations.</p><div className="callout"><strong>The central boundary</strong><p>ScadMill sends a bounded render request to an unmodified OpenSCAD subprocess. OpenSCAD returns geometry and logs. It is a separate process and a separate download; ScadMill does not reinterpret source or silently accept a different engine version.</p></div><h3>Data flow</h3><ol><li>The editor captures source and project assets.</li><li>The native adapter stages a contained request and launches the pinned OpenSCAD executable.</li><li>Output is validated, parsed, and presented as 2D SVG or 3D mesh geometry.</li><li>Exports originate only from full-quality results.</li></ol><h3>Trust boundaries</h3><ul><li><strong>User trust:</strong> source and projects are user-owned files.</li><li><strong>Engine trust:</strong> the exact official engine snapshot is hash-verifiable and runs out of process.</li><li><strong>Network trust:</strong> optional AI requests go to the configured endpoint with selected context only.</li><li><strong>Platform trust:</strong> secrets use the OS credential store; native paths and process operations stay behind typed commands.</li></ul><p>Read the <a href="/architecture">full architecture guide</a> for composition, state ownership, workers, packaging, provenance, and future extension seams.</p></section>
    <section id="troubleshooting"><p className="section-number">PART 4 · TROUBLESHOOTING</p><h2>Common problems</h2><h3>Rendering is disabled</h3><p>Open Settings or the engine banner and select the exact {RELEASE.engineVersion} <code>openscad.exe</code>. Older stable versions are intentionally rejected. Editing remains available.</p><h3>A render failed</h3><p>Open the console history, inspect stdout/stderr and clickable diagnostics, correct the source, and retry once. Use Cancel for a hung render. Do not use preview output as an export substitute.</p><h3>The window or layout looks wrong</h3><p>Use the View menu to reset or reveal panels. Window bounds are restored only when they remain on a connected display.</p><h3>I found a security issue</h3><p>Use <a href={`${RELEASE.github}/security/advisories/new`}>GitHub private vulnerability reporting</a>. Do not put sensitive details in a public issue.</p></section>
    <section id="uninstall"><p className="section-number">PART 5 · UNINSTALL AND SUPPORT</p><h2>Remove ScadMill</h2><p>Open <strong>Windows Settings → Apps → Installed apps → ScadMill → Uninstall</strong>. The application and <code>.scad</code> association are removed; user project folders remain. Uninstall is not an all-data-erasure promise: first clear AI keys and each enabled project cache if you do not want those records retained.</p><p>For release integrity, exact engine hashes, current limitations, and rollback guidance, use the <a href={`${RELEASE.github}/blob/main/docs/WINDOWS-BETA.md`}>Windows beta guide</a>.</p></section>
  </article></div><Footer /></main>;
}
