export const OPENSCAD_BUILTIN_REFERENCE = "openscad-2021.01-official-reference";

export const OPENSCAD_BUILTIN_MODULES = [
  "children",
  "circle",
  "color",
  "cube",
  "cylinder",
  "difference",
  "echo",
  "hull",
  "import",
  "intersection",
  "linear_extrude",
  "minkowski",
  "mirror",
  "multmatrix",
  "offset",
  "polygon",
  "polyhedron",
  "projection",
  "render",
  "resize",
  "rotate",
  "rotate_extrude",
  "scale",
  "sphere",
  "square",
  "surface",
  "text",
  "translate",
  "union",
] as const;

export const OPENSCAD_BUILTIN_FUNCTIONS = [
  "abs",
  "acos",
  "asin",
  "atan",
  "atan2",
  "ceil",
  "chr",
  "concat",
  "cos",
  "cross",
  "echo",
  "exp",
  "floor",
  "is_bool",
  "is_function",
  "is_list",
  "is_num",
  "is_string",
  "is_undef",
  "len",
  "ln",
  "log",
  "lookup",
  "max",
  "min",
  "norm",
  "ord",
  "parent_module",
  "pow",
  "rands",
  "round",
  "search",
  "sign",
  "sin",
  "sqrt",
  "str",
  "tan",
  "version",
  "version_num",
] as const;

export const OPENSCAD_CONTEXTUAL_BUILTINS = ["assert", "assign"] as const;

export const OPENSCAD_BUILTIN_NAMES: ReadonlySet<string> = new Set([
  ...OPENSCAD_BUILTIN_MODULES,
  ...OPENSCAD_BUILTIN_FUNCTIONS,
  ...OPENSCAD_CONTEXTUAL_BUILTINS,
]);
