import type { Metadata } from "next";
import { ArchitectureMap, Footer, Header, ReleaseBar } from "../shared";
import { RELEASE } from "../../lib/release";

export const metadata: Metadata = { title: "Architecture", description: `The runtime, data, trust, and release architecture of ScadMill ${RELEASE.version}.` };

export default function Architecture() {
  return <main><Header /><ReleaseBar /><div className="doc-hero dark shell-wide"><div className="shell"><p className="eyebrow">Product architecture</p><h1>A workbench around an engine—not a fork of one.</h1><p>Applies to ScadMill {RELEASE.version}</p><ArchitectureMap /></div></div><article className="prose architecture-prose shell">
    <section><p className="section-number">SYSTEM OVERVIEW</p><h2>Clear ownership at every boundary</h2><p>ScadMill is a React application inside a Tauri desktop shell. The UI owns editing, viewer state, parameters, command history, settings, and review flows. Typed ports define platform capabilities. Windows adapters supply local files, dialogs, process control, Credential Manager, menus, and window behavior.</p><p>The official OpenSCAD {RELEASE.engineVersion} executable remains unmodified and out of process. This is both a technical and product promise: ordinary OpenSCAD source remains the durable artifact, and geometry semantics remain the engine&apos;s responsibility.</p></section>
    <section><p className="section-number">RENDER PATH</p><h2>Source to geometry</h2><div className="flow-list"><div><span>01</span><strong>Snapshot</strong><p>The active source, referenced project files, binary assets, parameters, quality, and timeout become an immutable request.</p></div><div><span>02</span><strong>Stage</strong><p>The native adapter validates contained paths and stages a complete temporary project without mutating user files.</p></div><div><span>03</span><strong>Execute</strong><p>The exact pinned OpenSCAD process runs with bounded time and cancellable process-tree ownership.</p></div><div><span>04</span><strong>Present</strong><p>Validated STL or sanitized SVG feeds the viewer; logs, diagnostics, statistics, and identity remain bound to that source snapshot.</p></div></div></section>
    <section><p className="section-number">STATE & STORAGE</p><h2>Local-first by design</h2><p>Project folders are user-owned. Settings, layout, recovery, recent projects, annotation metadata, and optional per-project render cache use platform adapters rather than leaking storage APIs through product logic. Secrets are isolated per named AI configuration in Windows Credential Manager. The render cache is off by default, capped, integrity-checked, and never eligible for scratch work.</p></section>
    <section><p className="section-number">RESPONSIVENESS</p><h2>Heavy work stays away from interaction</h2><p>Native renders run outside the UI process. Browser-source workers handle structural indexing, archive work, mesh parsing, and the separately validated WebAssembly adapter. Automatic renders are debounced; superseded work is cancelled; animation is backpressured. The user sees stale, failed, cancelled, and unavailable states instead of a fabricated success.</p></section>
    <section><p className="section-number">NETWORK & PRIVACY</p><h2>No ambient cloud dependency</h2><p>ScadMill has no telemetry and no ScadMill service. Optional AI is provider-direct through a bounded native broker that refuses redirects and accepts only the configured endpoint. The local MCP bridge is loopback-only, off by default, and mutations require explicit permission plus review. The public beta is a desktop product; there is no hosted web application.</p></section>
    <section><p className="section-number">SUPPLY CHAIN</p><h2>Release evidence is part of the architecture</h2><p>The project records provenance, checks dependency licenses, pins the engine and Rust toolchain, packages from a clean source tree, signs the Windows installer, and verifies the public bytes independently. This beta also passed hosted CI, an isolated owner similarity gate, a literal one-hour reliability soak, Radeon 780M performance evidence, and a clean Windows Sandbox install-to-uninstall walkthrough.</p></section>
    <section><p className="section-number">EXTENSION SEAMS</p><h2>Built beyond the first beta without pretending it has arrived</h2><p>The development branch now completes M5 and includes M6&apos;s honest, worker-backed printability report for full renders. The same ports and workers support later public web distribution, the remaining headless CLI, slicer, engine-manager, color/3MF, and manufacturing-estimate work. None of that post-beta development is claimed as part of the published Windows beta.</p></section>
  </article><Footer /></main>;
}
